### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/october-feedbug#1]
Need to do:

 * [ ] AJAX loading RSS feed
 * [ ] Custom fields (tags)
 * [ ] Access to fields (tags) channel
 * [ ] Backend Widget (**?**)

**Comment by mrmlnc** [comment]
Go to Node.js
